var beers = [
    {
        name: "Witbier",
        short_description: "Cerveza rubia refrescante con aromas y sabores cítricos y especiados.",
        long_description: '',
        image: "/resources/images/beers/01.png",
        color: "darkslateblue",
        ibu: 14,
        alcohol: 5,
        hop: 80,
        malt: 20,
        body: 80,
        srm: 3
    },
    {
        name: "White IPA",
        short_description: "Cerveza rubia con notas a pomelo, limón y sutiles toques especiados. Amargor pronunciado ideal para amantes del lúpulo americano.",
        long_description: '',
        image: "/resources/images/beers/06.png",
        color: "#0a8f6a",
        ibu: 30,
        alcohol: 5.8,
        hop: 30,
        malt: 40,
        body: 50,
        srm: 3
    },
    {
        name: "American IPA",
        short_description: "Cerveza ámbar-rubí con notas a frutos secos, bizcocho y caramelo aportados por las maltas especiales.",
        long_description: '',
        image: "/resources/images/beers/03.png",
        color: "darkgreen",
        ibu: 20,
        alcohol: 5,
        hop: 30,
        malt: 40,
        body: 50,
        srm: 19
    },
    {
        name: "Pale Ale",
        short_description: "Cerveza ámbar-rubí con notas a frutos secos, bizcocho y caramelo aportados por las maltas especiales.",
        long_description: '',
        image: "/resources/images/beers/07.png",
        color: "#5c4021",
        ibu: 20,
        alcohol: 5,
        hop: 30,
        malt: 40,
        body: 50,
        srm: 19
    },
    {
        name: "Scottish",
        short_description: "Cerveza ámbar-rubí con notas a frutos secos, bizcocho y caramelo aportados por las maltas especiales.",
        long_description: '',
        image: "/resources/images/beers/05.png",
        color: "darkred",
        ibu: 20,
        alcohol: 5,
        hop: 30,
        malt: 40,
        body: 50,
        srm: 20
    },
    {
        name: "Porter",
        short_description: "Cerveza marrón de textura sedosa con un acentuado sabor a caramelo y chocolate.",
        long_description: '',
        image: "/resources/images/beers/04.png",
        color: "chocolate",
        ibu: 22,
        alcohol: 5,
        hop: 30,
        malt: 40,
        body: 50,
        srm: 30
    },
    {
        name: "Dry Stout",
        short_description: "Cerveza negra de final seco con sabor y aroma a café y chocolate amargo. Galardonada como la Mejor Cerveza Uruguaya 2018 en la Copa Uruguaya de Cervezas.",
        long_description: '',
        image: "/resources/images/beers/02.png",
        color: "darkslateblue",
        ibu: 25,
        alcohol: 4.5,
        hop: 30,
        malt: 40,
        body: 50,
        srm: 35
    }
];